# rmd_skeleton.R
# R Markdown document assembly utilities shared across converter packages

#' Generate a YAML front matter header for an R Markdown document
#'
#' @title Generate YAML header
#' @description Builds the YAML front matter block for an R Markdown document
#'   with standard html_document output settings including a table of contents,
#'   code folding, and a clean theme. The output is a character string that can
#'   be written directly to an `.Rmd` file.
#'
#' @param title Character string. Document title.
#' @param author Character string. Document author line. Defaults to
#'   `"Generated by stat2rmarkdown"`.
#' @param date Character string. Date expression for the document. Defaults to
#'   an inline R expression that formats the current date.
#' @param theme Character string. Bootstrap theme name for html_document output.
#'   Defaults to `"lumen"`.
#' @return Character string containing the complete YAML header block,
#'   including the leading and trailing `---` delimiters.
#' @export
#' @examples
#' cat(generate_yaml_header("My Analysis"))
#' cat(generate_yaml_header(
#'   title = "SPSS Conversion",
#'   author = "Generated by spss2rmarkdown",
#'   theme = "cosmo"
#' ))
generate_yaml_header <- function(title,
                                 author = "Generated by stat2rmarkdown",
                                 date = "`r format(Sys.Date(), '%B %d, %Y')`",
                                 theme = "lumen") {
  stopifnot(is.character(title), length(title) == 1L)
  glue::glue(
    '---
title: "{title}"
author: "{author}"
date: "{date}"
output:
  html_document:
    theme: {theme}
    highlight: tango
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: hide
    self_contained: true
    df_print: paged
---
')
}


#' Generate an inline CSS style block for the knitted HTML report
#'
#' @title Generate style block
#' @description Returns a raw `<style>` block (as a length-1 character string)
#'   to be emitted immediately after the YAML header in the document body.
#'   Because it is inline, `self_contained: true` keeps it embedded in the
#'   single output file with no extra dependency. It provides a readable font
#'   stack, comfortable line-height, and clean styling for the statistical
#'   tables emitted by [render_jmv_tables()] (class `s2r-table`) plus any
#'   residual verbatim (`pre`) output.
#' @return Character string containing a `<style>...</style>` block followed by
#'   a trailing blank line.
#' @export
generate_style_block <- function() {
  paste0(
    "<style>\n",
    "body, .main-container { font-family: -apple-system, BlinkMacSystemFont, ",
    "'Segoe UI', Roboto, Helvetica, Arial, sans-serif; ",
    "font-size: 15px; line-height: 1.6; color: #1f2933; }\n",
    ".main-container { max-width: 960px; }\n",
    "h1, h2, h3, h4 { font-weight: 600; line-height: 1.25; margin-top: 1.6em; }\n",
    "h1 { font-size: 1.7em; } h2 { font-size: 1.4em; } ",
    "h3 { font-size: 1.18em; } h4 { font-size: 1.02em; color: #3e4c59; }\n",
    "table.s2r-table { border-collapse: collapse; margin: 0.6em 0 1.4em; ",
    "font-size: 0.92em; width: auto; }\n",
    "table.s2r-table th, table.s2r-table td { padding: 6px 12px; ",
    "border: 1px solid #e4e7eb; text-align: right; }\n",
    "table.s2r-table th { background: #f5f7fa; font-weight: 600; ",
    "text-align: left; }\n",
    "table.s2r-table td:first-child, table.s2r-table th:first-child { ",
    "text-align: left; }\n",
    "table.s2r-table tbody tr:nth-child(even) { background: #fafbfc; }\n",
    "pre { white-space: pre-wrap; word-break: break-word; font-size: 0.85em; ",
    "background: #f5f7fa; border-radius: 6px; padding: 12px; }\n",
    "code { font-size: 0.88em; }\n",
    "</style>\n\n"
  )
}


#' Render every statistical table inside a jmv result object as HTML
#'
#' @title Render jmv tables as HTML
#' @description Recursively walks a jmv results object (from `jmv::ttestIS`,
#'   `jmv::ANOVA`, `jmv::descriptives`, etc.) and emits each `Table` element as
#'   a real HTML table via [knitr::kable()] (which ships with knitr -- no extra
#'   dependency). This replaces the default auto-printed console output, whose
#'   Unicode box-drawing rule lines render as mojibake (`a-circumflex` byte pairs) when the worker
#'   locale is not UTF-8, and which is far less readable than a styled table.
#'
#'   Intended to be called from an analysis chunk with the `results='asis'`
#'   chunk option so the kable HTML is passed through verbatim.
#'
#' @param x A jmv results object (or any element/group within one).
#' @param heading_level Integer markdown heading level for each table's title.
#'   Defaults to 4 (matches `toc_depth: 4`).
#' @param .depth Internal recursion-depth guard. Do not set.
#' @return Invisibly `NULL`; called for its side effect of `cat()`-ing HTML.
#' @export
render_jmv_tables <- function(x, heading_level = 4, .depth = 0L) {
  if (.depth > 8L) return(invisible())
  if (inherits(x, "Table")) {
    # jmv includes structural tables (Levene's, Shapiro-Wilk, itemReliability,
    # etc.) in the results object even when the corresponding option was not
    # requested; it flags them `visible = FALSE` and its own UI hides them.
    # Rendering them anyway emits shells full of "." placeholder cells that
    # have no counterpart in jamovi's own output. Honour `$visible`: skip a
    # table only when it is *definitively* not visible (never on NA/error, to
    # stay conservative for Table-likes without the property).
    vis <- tryCatch(x$visible, error = function(e) NULL)
    if (is.logical(vis) && length(vis) == 1L && !is.na(vis) && !isTRUE(vis)) {
      return(invisible())
    }
    # Parse jmv's own correctly-laid-out asString() (variables/stats oriented
    # as jamovi intends) into HTML. asDF is transposed/flat for some table
    # types (e.g. descriptives), so asString is the better source.
    s <- tryCatch(x$asString(), error = function(e) NULL)
    h <- .jmv_asstring_to_html(s)
    if (is.null(h)) {
      if (!is.null(s) && nzchar(s)) cat("\n\n```\n", s, "\n```\n\n", sep = "")
      return(invisible())
    }
    cat("\n\n", h, "\n\n", sep = "")
    return(invisible())
  }
  # Recurse ONLY into Group/Array (NOT the broad ResultsElement class -- every
  # element incl. Table is a ResultsElement, and some leaves recurse forever).
  if (inherits(x, "Group") || inherits(x, "Array")) {
    nms <- tryCatch(names(x), error = function(e) NULL)
    if (!is.null(nms)) {
      for (nm in nms) {
        child <- tryCatch(x[[nm]], error = function(e) NULL)
        if (!is.null(child)) render_jmv_tables(child, heading_level, .depth + 1L)
      }
    }
    return(invisible())
  }
  if (is.data.frame(x)) {
    cat("\n\n", knitr::kable(x, format = "html", escape = FALSE,
        table.attr = 'class="s2r-table"'), "\n\n", sep = "")
  }
  invisible()
}

#' Parse a jmv Table$asString() ASCII layout into a clean HTML table string.
#' @keywords internal
.jmv_asstring_to_html <- function(s) {
  if (is.null(s) || !nzchar(s)) return(NULL)
  lines <- strsplit(s, "\n", fixed = TRUE)[[1]]
  is_sep <- function(l) nchar(gsub("[[:space:]\u2500-\u257f]", "", l, perl = TRUE)) == 0L
  content <- lines[!vapply(lines, is_sep, logical(1))]
  content <- content[nchar(trimws(content)) > 0]
  if (length(content) < 2L) return(NULL)
  title <- trimws(content[[1]])
  header_line <- content[[2]]
  row_lines <- if (length(content) >= 3L) content[3:length(content)] else character(0)
  split_cols <- function(l) {
    parts <- strsplit(sub("^\\s+", "", l), "\\s{2,}", perl = TRUE)[[1]]
    parts[nchar(parts) > 0]
  }
  header <- split_cols(header_line)
  rows <- lapply(row_lines, split_cols)
  ncol_max <- max(c(length(header), vapply(rows, length, integer(1))), 0L)
  if (ncol_max < 1L) return(NULL)
  if (length(header) < ncol_max) header <- c(rep("", ncol_max - length(header)), header)
  esc <- function(x) {
    x <- gsub("&", "&amp;", x, fixed = TRUE)
    x <- gsub("<", "&lt;", x, fixed = TRUE)
    gsub(">", "&gt;", x, fixed = TRUE)
  }
  th <- paste0("<th>", esc(header), "</th>", collapse = "")
  body <- vapply(rows, function(r) {
    r <- c(r, rep("", ncol_max - length(r)))
    paste0("<tr>", paste0("<td>", esc(r), "</td>", collapse = ""), "</tr>")
  }, character(1))
  cap <- if (nzchar(title)) paste0("<caption>", esc(title), "</caption>") else ""
  paste0('<table class="s2r-table">', cap, "<thead><tr>", th,
         "</tr></thead><tbody>", paste(body, collapse = ""), "</tbody></table>")
}


#' Render a fitted model as an HTML coefficient table
#'
#' @title Render model table as HTML
#' @description Emits a fitted model (`lm`, `glm`, `fixest`, `lmer`, ...) as a
#'   styled HTML table. Prefers `modelsummary::msummary(output = "html")` when
#'   installed; falls back to
#'   `broom::tidy()` + [knitr::kable()]; and finally to a plain `print(summary())`
#'   (ASCII -- no mojibake) for model classes neither library supports. Intended
#'   for use in a `results='asis'` chunk.
#'
#' @param model A fitted model object.
#' @return Invisibly `NULL`; called for its `cat()` side effect.
#' @export
render_model_table <- function(model) {
  if (requireNamespace("modelsummary", quietly = TRUE)) {
    out <- tryCatch(
      as.character(modelsummary::msummary(model, output = "html")),
      error = function(e) NULL
    )
    if (!is.null(out)) {
      cat(out, "\n\n", sep = "")
      return(invisible())
    }
  }
  if (requireNamespace("broom", quietly = TRUE)) {
    td <- tryCatch(broom::tidy(model), error = function(e) NULL)
    if (!is.null(td) && nrow(td) > 0L) {
      cat(
        knitr::kable(td, format = "html", escape = FALSE,
                     table.attr = 'class="s2r-table"'),
        "\n\n",
        sep = ""
      )
      return(invisible())
    }
  }
  print(summary(model))
  invisible()
}


#' Generate an R Markdown setup code chunk
#'
#' @title Generate setup chunk
#' @description Creates the initial setup code chunk for an R Markdown document.
#'   This chunk sets `knitr` options (echo, message, warning suppression, figure
#'   dimensions) and loads the specified packages.
#'
#' @param packages Character vector of package names to load via
#'   `library()`. Defaults to a minimal set: `haven`, `dplyr`, `tidyr`,
#'   `ggplot2`, `stringr`.
#' @param options Named list of knitr chunk options to override the defaults.
#'   Supported options: `echo`, `message`, `warning`, `error`, `fig.width`,
#'   `fig.height`. Any option not provided uses the default value.
#' @param extra_code Character string. Additional R code to append after the
#'   library calls inside the setup chunk. Defaults to `NULL` (no extra code).
#' @return Character string containing the complete setup chunk.
#' @export
#' @examples
#' cat(generate_setup_chunk())
#' cat(generate_setup_chunk(
#'   packages = c("haven", "dplyr", "fixest"),
#'   extra_code = "setFixest_notes(FALSE)"
#' ))
generate_setup_chunk <- function(packages = c("haven", "dplyr", "tidyr",
                                              "ggplot2", "stringr"),
                                 options = list(),
                                 extra_code = NULL) {
  # Merge user options with defaults
  defaults <- list(
    echo = TRUE,
    message = FALSE,
    warning = FALSE,
    error = TRUE,
    fig.width = 10,
    fig.height = 7
  )
  opts <- utils::modifyList(defaults, options)

  # Build knitr options string
  opts_lines <- vapply(names(opts), function(nm) {
    val <- opts[[nm]]
    val_str <- if (is.logical(val)) {
      toupper(as.character(val))
    } else {
      as.character(val)
    }
    sprintf("  %s = %s", nm, val_str)
  }, character(1))
  opts_str <- paste(opts_lines, collapse = ",\n")

  # Build library calls
  lib_lines <- paste0("library(", packages, ")", collapse = "\n")

  # Build extra code section

  extra_section <- if (!is.null(extra_code) && nchar(trimws(extra_code)) > 0) {
    paste0("\n\n", extra_code)
  } else {
    ""
  }

  paste0(
    "```{r setup, include=FALSE}\n",
    "knitr::opts_chunk$set(\n",
    opts_str, "\n",
    ")\n\n",
    "# Load packages\n",
    lib_lines,
    extra_section, "\n",
    "```\n"
  )
}


#' Generate an R Markdown session info footer
#'
#' @title Generate session info footer
#' @description Creates a closing section for an R Markdown document that
#'   displays `sessionInfo()` output and a credit line for the generating tool.
#'   This is useful for reproducibility.
#'
#' @param tool_name Character string. Name of the converter tool to credit in
#'   the footer. Defaults to `"stat2rmarkdown"`.
#' @param repo_url Character string. URL for the tool repository. Defaults to
#'   `"https://github.com/giladfeldman/stat2rmarkdown"`.
#' @return Character string containing the session info section as R Markdown.
#' @export
#' @examples
#' cat(generate_session_footer())
#' cat(generate_session_footer(
#'   tool_name = "stata2rmarkdown",
#'   repo_url = "https://github.com/giladfeldman/STATA2Rmarkdown"
#' ))
generate_session_footer <- function(tool_name = "stat2rmarkdown",
                                    repo_url = "https://github.com/giladfeldman/stat2rmarkdown") {
  paste0(
    "\n---\n\n",
    "# Session Info\n\n",
    "```{r session-info}\n",
    "sessionInfo()\n",
    "```\n\n",
    "---\n\n",
    "*Report generated by [", tool_name, "](", repo_url,
    ") -- a deterministic converter for academic replication.*\n"
  )
}
