# rmd_skeleton.R
# R Markdown document assembly utilities shared across converter packages

#' Generate a YAML front matter header for an R Markdown document
#'
#' @title Generate YAML header
#' @description Builds the YAML front matter block for an R Markdown document
#'   with standard html_document output settings including a table of contents,
#'   code folding, and a clean theme. The output is a character string that can
#'   be written directly to an `.Rmd` file.
#'
#' @param title Character string. Document title.
#' @param author Character string. Document author line. Defaults to
#'   `"Generated by stat2rmarkdown"`.
#' @param date Character string. Date expression for the document. Defaults to
#'   an inline R expression that formats the current date.
#' @param theme Character string. Bootstrap theme name for html_document output.
#'   Defaults to `"lumen"`.
#' @return Character string containing the complete YAML header block,
#'   including the leading and trailing `---` delimiters.
#' @export
#' @examples
#' cat(generate_yaml_header("My Analysis"))
#' cat(generate_yaml_header(
#'   title = "SPSS Conversion",
#'   author = "Generated by spss2rmarkdown",
#'   theme = "cosmo"
#' ))
generate_yaml_header <- function(title,
                                 author = "Generated by stat2rmarkdown",
                                 date = "`r format(Sys.Date(), '%B %d, %Y')`",
                                 theme = "lumen") {
  stopifnot(is.character(title), length(title) == 1L)
  glue::glue(
    '---
title: "{title}"
author: "{author}"
date: "{date}"
output:
  html_document:
    theme: {theme}
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: hide
    self_contained: true
    df_print: paged
---
')
}


#' Generate an R Markdown setup code chunk
#'
#' @title Generate setup chunk
#' @description Creates the initial setup code chunk for an R Markdown document.
#'   This chunk sets `knitr` options (echo, message, warning suppression, figure
#'   dimensions) and loads the specified packages.
#'
#' @param packages Character vector of package names to load via
#'   `library()`. Defaults to a minimal set: `haven`, `dplyr`, `tidyr`,
#'   `ggplot2`, `stringr`.
#' @param options Named list of knitr chunk options to override the defaults.
#'   Supported options: `echo`, `message`, `warning`, `error`, `fig.width`,
#'   `fig.height`. Any option not provided uses the default value.
#' @param extra_code Character string. Additional R code to append after the
#'   library calls inside the setup chunk. Defaults to `NULL` (no extra code).
#' @return Character string containing the complete setup chunk.
#' @export
#' @examples
#' cat(generate_setup_chunk())
#' cat(generate_setup_chunk(
#'   packages = c("haven", "dplyr", "fixest"),
#'   extra_code = "setFixest_notes(FALSE)"
#' ))
generate_setup_chunk <- function(packages = c("haven", "dplyr", "tidyr",
                                              "ggplot2", "stringr"),
                                 options = list(),
                                 extra_code = NULL) {
  # Merge user options with defaults
  defaults <- list(
    echo = TRUE,
    message = FALSE,
    warning = FALSE,
    error = TRUE,
    fig.width = 10,
    fig.height = 7
  )
  opts <- modifyList(defaults, options)

  # Build knitr options string
  opts_lines <- vapply(names(opts), function(nm) {
    val <- opts[[nm]]
    val_str <- if (is.logical(val)) {
      toupper(as.character(val))
    } else {
      as.character(val)
    }
    sprintf("  %s = %s", nm, val_str)
  }, character(1))
  opts_str <- paste(opts_lines, collapse = ",\n")

  # Build library calls
  lib_lines <- paste0("library(", packages, ")", collapse = "\n")

  # Build extra code section

  extra_section <- if (!is.null(extra_code) && nchar(trimws(extra_code)) > 0) {
    paste0("\n\n", extra_code)
  } else {
    ""
  }

  paste0(
    "```{r setup, include=FALSE}\n",
    "knitr::opts_chunk$set(\n",
    opts_str, "\n",
    ")\n\n",
    "# Load packages\n",
    lib_lines,
    extra_section, "\n",
    "```\n"
  )
}


#' Generate an R Markdown session info footer
#'
#' @title Generate session info footer
#' @description Creates a closing section for an R Markdown document that
#'   displays `sessionInfo()` output and a credit line for the generating tool.
#'   This is useful for reproducibility.
#'
#' @param tool_name Character string. Name of the converter tool to credit in
#'   the footer. Defaults to `"stat2rmarkdown"`.
#' @param repo_url Character string. URL for the tool repository. Defaults to
#'   `"https://github.com/giladfeldman/2rmarkdown"`.
#' @return Character string containing the session info section as R Markdown.
#' @export
#' @examples
#' cat(generate_session_footer())
#' cat(generate_session_footer(
#'   tool_name = "stata2rmarkdown",
#'   repo_url = "https://github.com/giladfeldman/STATA2Rmarkdown"
#' ))
generate_session_footer <- function(tool_name = "stat2rmarkdown",
                                    repo_url = "https://github.com/giladfeldman/2rmarkdown") {
  paste0(
    "\n---\n\n",
    "# Session Info\n\n",
    "```{r session-info}\n",
    "sessionInfo()\n",
    "```\n\n",
    "---\n\n",
    "*Report generated by [", tool_name, "](", repo_url,
    ") -- a deterministic converter for academic replication.*\n"
  )
}
